### ISSUE TITLE
Handle remove as well

### ISSUE THREAD

**Issue by ismay** [akameco/prioritize-yarn#5]
version:
- `node` version: 11.9.0
- `npm` (or `yarn`) version: 6.7.0 & 1.13.0

**Do you want to request a *feature* or report a *bug*?:**

Feature

**What is the current behavior?:**

Doesn't work with uninstalls.

**What is the expected behavior?:**

Similar to it handling installs with `--save` and `--save-dev`, etc. It would be nice if this module also handled uninstalls, because yarn expects `remove` instead of uninstall and there might be optional flags as well.

**Suggested solution:**

See above.

**Comment by akameco** [comment]
@ismay Thanks for the suggestion. Supported.

**Comment by ismay** [comment]
Awesome, thanks!
