### ISSUE TITLE
Handle npm link as well

### ISSUE THREAD

**Issue by ismay** [akameco/prioritize-yarn#6]
Related to #5, `npm link` and `npm link <packagename>` should probably also be redirected to `yarn link`. Otherwise npm installs all deps and creates a lockfile before linking.

version:
- `node` version: 11.9.0
- `npm` (or `yarn`) version: 6.7.0 & 1.13.0

**Do you want to request a *feature* or report a *bug*?:**

Feature

**What is the current behavior?:**

Doesn't work with `link`.

**What is the expected behavior?:**

Similar to it handling installs with `--save` and `--save-dev`, etc. It would be nice if this module also handled `link`.

**Suggested solution:**

See above.

**Comment by akameco** [comment]
@ismay Thanks for the suggestion. Supported v1.1.0 😄

**Comment by ismay** [comment]
😊 Awesome, thanks again! 🎉
